config/routes.rb
JKMillerPhoto::Application.routes.draw do
  # EXAMPLES
  # resources :products
  # root :to => 'welcome#index'

  # MORE INFORMATION
  # Run "rake routes" to see the routes available
  # http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

  devise_for :users

  resources :photos, :users


  get '/gallery' => 'home#begin'
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  # =============
  # image file uploads
  # =============
  mount_uploader :image, ImageUploader

  # =============
  # ActiveModel Observers:
  # =============
  before_validation :populate_name_if_blank
  before_save :track_published_at  if :published_changed?

  # =============
  # Validations
  # =============
  validates :name, presence: true

  protected

    def populate_name_if_blank
      self.name = file_name unless self.name.present?
    end

    def track_published_at
      if published?
        self.published_at = Time.zone.now
      else
        self.published_at = nil
      end
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_path, notice: 'Photo was successfully created.' }
        format.json { render action: 'index', status: :created, location: photos_path }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photos_path, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :image, :description, :short_description, :published, :published_at,
        :order, :content_type, :file_size, :width, :height, :filename_suffix, :file_format, :is_transparency,
        :resolution, :compression_percent, :file_name, :unique_color_count)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= simple_form_for @photo, html: { class: 'well form-horizontal' } do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :image, as: :file
    = f.input :published, as: :boolean, label: 'Publish this photo?'
    = f.input :order

    = f.input :description
    = f.input :short_description

  .form-actions
    = f.button :submit

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', @photo
\|
= link_to 'Back', photos_path

app/views/photos/index.html.haml
- title "Listing Photos"

- main_action create_link([:new, :photo], class: 'btn-info', link_text: 'New Photo')

%table.table.table-striped
  %tr
    %th Order
    %th Name
    %th Image
    %th Description
    %th Short description
    %th Published
    %th Published at
    %th Actions

  - @photos.each do |photo|
    %tr
      %td= photo.order
      %td= photo.name
      %td= image_tag(photo.image_url(:thumb).to_s, class: 'img-thumbnail')
      %td= photo.description
      %td= photo.short_description
      %td= photo.published
      %td= photo.published_at
      %td= default_crud_actions(photo, link_text: '')

%br

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @photo.name
%p
  %b Image:
  = @photo.image
%p
  %b Description:
  = @photo.description
%p
  %b Short description:
  = @photo.short_description
%p
  %b Published:
  = @photo.published
%p
  %b Published at:
  = @photo.published_at
%p
  %b Order:
  = @photo.order

= link_to 'Edit', edit_photo_path(@photo)
\|
= link_to 'Back', photos_path