config/routes.rb
JKMillerPhoto::Application.routes.draw do
  # EXAMPLES
  # resources :products
  # root :to => 'welcome#index'

  # MORE INFORMATION
  # Run "rake routes" to see the routes available
  # http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "home#index"

  devise_for :users

  resources :photos, :users


  get '/gallery' => 'home#begin'
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Jkmillerphoto", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Jkmillerphoto"
      %meta{:content => content_for?(:description) ? yield(:description) : "JK Miller Photo", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"

        - # load controller specific CSS files if the asset exists
        = stylesheet_link_tag controller.controller_name if JKMillerPhoto::Application.assets.find_asset("#{controller.controller_name}.css")

        = javascript_include_tag "application"
        = yield(:head) # allows us to load any necessary js files/plugins before calling the controller-specific js

        - # load controller specific JS files if the asset exists
        = javascript_include_tag controller.controller_name if JKMillerPhoto::Application.assets.find_asset("#{controller.controller_name}.js")

        / respond.js
        = respond_include_tags

        = csrf_meta_tags
        = yield(:head)
  %body{ class: "#{controller_name} #{action_name}" }
    - if content_for?(:branding_bubble)
      = yield(:branding_bubble)


    - if user_signed_in?
      / Fixed navbar
      .navbar.navbar-inverse.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{ type: "button", data: { toggle: "collapse", target: ".navbar-collapse" } }
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar

            = link_to 'JK Miller Photo', root_path, class: 'navbar-brand'

          .navbar-collapse.collapse
            %ul.nav.navbar-nav
              %li= link_to 'Home', root_path
              %li= link_to 'Photos', photos_path if can?(:manage, Photo)
              %li= link_to 'Users', users_path if can?(:manage, User)

            %ul.nav.navbar-nav.navbar-right
              %li= link_to 'My Account', edit_user_path(current_user)
              %li= link_to "<i class='icon-signout'></i> Logout".html_safe, destroy_user_session_path, method: Rails.env.test? ? :get : :delete

    #main{:role => "main"}
      .container
        - if content_for?(:title)
          .page-header
            %h1
              = yield(:title)

              - if content_for?(:main_action)
                .pull-right
                  = yield(:main_action)

        .content
          .row
            .span12
              = render 'layouts/messages' if user_signed_in?
              = yield
          %footer#footer
            - if content_for?(:footer_contact_info)
              = yield(:footer_contact_info)

      / ! end of .container
    / ! end of #main